name: 'bundlesize'
on: # rebuild any PRs and main branch changes
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  bundlesize: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: new
      - uses: actions/checkout@v2
        with:
          path: old
          ref: master # Change this if you want to compare to a different bundle
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn --frozen-lockfile --cwd ./new # install PR depedendencies
      - run: yarn --cwd ./new build > new.txt # build PR branch
      - run: yarn --frozen-lockfile --cwd ./old # install main branch dependencies
      - run: yarn --cwd ./old build > old.txt # build main branch
      - uses: ho-nl/next-bundlesize-action@1.x # create diff markdown
        id: 'bundlesize'
      - uses: unsplash/comment-on-pr@1.x # create comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{steps.bundlesize.outputs.diff}}
          check_for_duplicate_msg: true
